# Lesson 3: Demo

In [1]:
#General imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

### Class/Dummy Variables
We want to represent categorical variables numerically, but we can't simply code them as 0=rural, 1=suburban, 2=urban because that would imply an **ordered relationship** between suburban and urban (suggesting that urban is somehow "twice" the suburban category, which doesn't make sense).

Why do we only need **two dummy variables, not three?** Because two dummies capture all of the information about the Area feature, and implicitly defines rural as the reference level.

In general, if you have a categorical feature with k levels, you create k-1 dummy variables.

#### Create three dummy variables using get_dummies, then exclude the first dummy column
my_categorical_var_dummies = pd.get_dummies(my_categorical_var, prefix='Area').iloc[:, 1:]

In [9]:
# read data into a DataFrame
data = pd.read_csv('http://www-bcf.usc.edu/~gareth/ISL/Advertising.csv', index_col=0)
data.head()

      TV  Radio  Newspaper  Sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

### Handling Categorical Predictors with Two Categories

Up to now, all of our predictors have been numeric. What if one of our predictors was categorical?

Let's create a new feature called "Size," and randomly assign observations to be small or large:

In [10]:
np.random.seed(5)
randnums = np.random.rand(5)
randnums
larger = randnums > 0.5
larger

array([False,  True, False,  True, False], dtype=bool)

In [11]:
# set a seed for reproducibility
#np.random.seed(0) makes the random numbers predictable
np.random.seed(12345)

# create a Series of booleans in which roughly half are True
nums = np.random.rand(len(data))
mask_large = nums > 0.5

# initially set Size to small, then change roughly half to be large
data['Size'] = 'small'
data.loc[mask_large, 'Size'] = 'large'
data.head()

      TV  Radio  Newspaper  Sales   Size
1  230.1   37.8       69.2   22.1  large
2   44.5   39.3       45.1   10.4  small
3   17.2   45.9       69.3    9.3  small
4  151.5   41.3       58.5   18.5  small
5  180.8   10.8       58.4   12.9  large

For scikit-learn, we need to represent all data numerically. 

If the feature only has two categories, we can simply create a dummy variable that represents the categories as a binary value.

In [12]:
# create a new Series called IsLarge
data['IsLarge'] = data.Size.map({'small':0, 'large':1})
data.head()

      TV  Radio  Newspaper  Sales   Size  IsLarge
1  230.1   37.8       69.2   22.1  large        1
2   44.5   39.3       45.1   10.4  small        0
3   17.2   45.9       69.3    9.3  small        0
4  151.5   41.3       58.5   18.5  small        0
5  180.8   10.8       58.4   12.9  large        1

### Handling Categorical Predictors with More than Two Categories

Let's create a new feature called Area, and randomly assign observations to be rural, suburban, or urban:

In [13]:
# set a seed for reproducibility
np.random.seed(123456)


# assign roughly one third of observations to each group
nums = np.random.rand(len(data))
mask_suburban = (nums > 0.33) & (nums < 0.66)
mask_urban = nums > 0.66
data['Area'] = 'rural'
data.loc[mask_suburban, 'Area'] = 'suburban'
data.loc[mask_urban, 'Area'] = 'urban'
data.head()

      TV  Radio  Newspaper  Sales   Size  IsLarge      Area
1  230.1   37.8       69.2   22.1  large        1     rural
2   44.5   39.3       45.1   10.4  small        0     urban
3   17.2   45.9       69.3    9.3  small        0     rural
4  151.5   41.3       58.5   18.5  small        0     urban
5  180.8   10.8       58.4   12.9  large        1  suburban

In [18]:
df_area = pd.get_dummies(data['Area'])
df_area
df_new = pd.concat([data, df_area], axis=1)
df_new

,TV,Radio,Newspaper,Sales,Size,IsLarge,Area,rural,suburban,urban
1,230.1,37.8,69.2,22.1,large,1,rural,1,0,0
2,44.5,39.3,45.1,10.4,small,0,urban,0,0,1
3,17.2,45.9,69.3,9.3,small,0,rural,1,0,0
4,151.5,41.3,58.5,18.5,small,0,urban,0,0,1
5,180.8,10.8,58.4,12.9,large,1,suburban,0,1,0
6,8.7,48.9,75.0,7.2,large,1,suburban,0,1,0
7,57.5,32.8,23.5,11.8,large,1,suburban,0,1,0
8,120.2,19.6,11.6,13.2,large,1,urban,0,0,1
9,8.6,2.1,1.0,4.8,large,1,rural,1,0,0
10,199.8,2.6,21.2,10.6,large,1,suburban,0,1,0
11,66.1,5.8,24.2,8.6,large,1,suburban,0,1,0
12,214.7,24.0,4.0,17.4,large,1,suburban,0,1,0
13,23.8,35.1,65.9,9.2,small,0,rural,1,0,0
14,97.5,7.6,7.2,9.7,small,0,urban,0,0,1
15,204.1,32.9,46.0,19.0,small,0,urban,0,0,1
16,195.4,47.7,52.9,22.4,large,1,suburban,0,1,0
17,67.8,36.6,114.0,12.5,large,1,rural,1,0,0
18,281.4,39.6,55.8,24.4,large,1,urban,0,0,1
19,69.2,20.5,18.3,11.3,large,1,suburban,0,1,0
20,147.3,23.9,19.1,14.6,large,1,rural,1,0,0
21,218.4,27.7,53.4,18.0,large,1,urban,0,0,1
22,237.4,5.1,23.5,12.5,large,1,rural,1,0,0
23,13.2,15.9,49.6,5.6,small,0,rural,1,0,0
24,228.3,16.9,26.2,15.5,small,0,suburban,0,1,0
25,62.3,12.6,18.3,9.7,small,0,suburban,0,1,0
26,262.9,3.5,19.5,12.0,large,1,rural,1,0,0
27,142.9,29.3,12.6,15.0,large,1,suburban,0,1,0
28,240.1,16.7,22.9,15.9,large,1,rural,1,0,0
29,248.8,27.1,22.9,18.9,large,1,suburban,0,1,0
30,70.6,16.0,40.8,10.5,small,0,urban,0,0,1
...,...,...,...,...,...,...,...,...,...,...
171,50.0,11.6,18.4,8.4,large,1,suburban,0,1,0
172,164.5,20.9,47.4,14.5,small,0,suburban,0,1,0
173,19.6,20.1,17.0,7.6,large,1,rural,1,0,0
174,168.4,7.1,12.8,11.7,large,1,urban,0,0,1
175,222.4,3.4,13.1,11.5,large,1,rural,1,0,0
176,276.9,48.9,41.8,27.0,small,0,urban,0,0,1
177,248.4,30.2,20.3,20.2,large,1,suburban,0,1,0
178,170.2,7.8,35.2,11.7,large,1,urban,0,0,1
179,276.7,2.3,23.7,11.8,large,1,suburban,0,1,0
180,165.6,10.0,17.6,12.6,small,0,suburban,0,1,0
181,156.6,2.6,8.3,10.5,small,0,urban,0,0,1
182,218.5,5.4,27.4,12.2,small,0,suburban,0,1,0
183,56.2,5.7,29.7,8.7,large,1,rural,1,0,0
184,287.6,43.0,71.8,26.2,small,0,urban,0,0,1
185,253.8,21.3,30.0,17.6,small,0,suburban,0,1,0
186,205.0,45.1,19.6,22.6,large,1,urban,0,0,1
187,139.5,2.1,26.6,10.3,small,0,suburban,0,1,0
188,191.1,28.7,18.2,17.3,large,1,rural,1,0,0
189,286.0,13.9,3.7,15.9,small,0,urban,0,0,1
190,18.7,12.1,23.4,6.7,small,0,rural,1,0,0
191,39.5,41.1,5.8,10.8,large,1,suburban,0,1,0
192,75.5,10.8,6.0,9.9,large,1,rural,1,0,0
193,17.2,4.1,31.6,5.9,small,0,suburban,0,1,0
194,166.8,42.0,3.6,19.6,small,0,suburban,0,1,0
195,149.7,35.6,6.0,17.3,large,1,rural,1,0,0
196,38.2,3.7,13.8,7.6,small,0,suburban,0,1,0
197,94.2,4.9,8.1,9.7,small,0,urban,0,0,1
198,177.0,9.3,6.4,12.8,small,0,suburban,0,1,0
199,283.6,42.0,66.2,25.5,small,0,rural,1,0,0
200,232.1,8.6,8.7,13.4,large,1,rural,1,0,0

We have to represent Area numerically, but we can't simply code it as 0=rural, 1=suburban, 2=urban because that would imply an ordered relationship between suburban and urban (and thus urban is somehow "twice" the suburban category).

Instead, we create another dummy variable:

In [21]:
# create three dummy variables using get_dummies, then exclude the first dummy column
area_dummies = pd.get_dummies(data.Area, prefix='Area').iloc[:, 2:]

# concatenate the dummy variable columns onto the original DataFrame (axis=0 means rows, axis=1 means columns)
data1 = pd.concat([data, area_dummies], axis=1)
data1.head()

      TV  Radio  Newspaper  Sales   Size  IsLarge      Area  Area_urban
1  230.1   37.8       69.2   22.1  large        1     rural           0
2   44.5   39.3       45.1   10.4  small        0     urban           1
3   17.2   45.9       69.3    9.3  small        0     rural           0
4  151.5   41.3       58.5   18.5  small        0     urban           1
5  180.8   10.8       58.4   12.9  large        1  suburban           0